<a href="https://colab.research.google.com/github/akbhrr/Numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#numpy



In [ ]:
import numpy as np #numerical python


#array - collection of data with same type of data(homogenious)
a=np.array([1,2,3,4,"a"])

print(a)


['4' '3']


#slicing

In [ ]:
#slicing-forward & backword

In [ ]:
b=np.array([1,2,3,4,5,6])
print(b[0:2:1])
print(b[-2:-4:-1])
print(b[3:5:1])
print(b[-5::-1])

[1 2]
[5 4]
[4 5]
[2 1]


#Dimension

In [ ]:
#dimension
a=np.array([0,2,3,4,5])
b=np.array([[1,2,3],[3,4,5]])
a.ndim #dimension=1 vector
b.ndim #dimesnion=2 matrix

print(a)
print(b.shape)

[0 2 3 4 5]
(2, 3)


In [ ]:
#create a matrix [[]] 2x2 [2,3],[4,5]
a=np.array([[2,3],[4,5]])
print(a)
print("shape of matrix is ",a.shape)
print("dimension =",a.ndim)
print("size of matrix is ",a.size)

[[2 3]
 [4 5]]
shape of matrix is  (2, 2)
dimension = 2
size of matrix is  4


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6


In [ ]:
#create 4x2 matrix
a=np.array([[1,2],[4,5],[2,3],[5,8]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[1 2]
 [4 5]
 [2 3]
 [5 8]]
2
(4, 2)
8


In [ ]:
#4x4
a=np.array([[1,2,3,4],[4,5,6,7],[2,3,4,5],[5,8,9,7]])
print(a)
print(a.ndim)
print(a.size)
print(a.shape)

[[1 2 3 4]
 [4 5 6 7]
 [2 3 4 5]
 [5 8 9 7]]
2
16
(4, 4)


In [ ]:
import numpy as np

a=np.array([[1,2,3,4],[1,2,4,5],[3,4,5,6]])
print(a.ndim)
print(a.shape)
print(a.size)
print(a)
print(a[0])
print(a[:,0])
print(a[1,1])
print(a[2,2:])
print("that is",a[1:,2:])

2
(3, 4)
12
[[1 2 3 4]
 [1 2 4 5]
 [3 4 5 6]]
[1 2 3 4]
[1 1 3]
2
[5 6]
that is [[4 5]
 [5 6]]


In [ ]:
import numpy as np
np.zeros([3,3,3],dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
a=np.zeros([3,2,2],dtype=int)#complex,int
print(a)

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [ ]:
a=np.ones([3,3,3],dtype=int)
a

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [ ]:
a=np.array([[2,2],[2,2]])
a

array([[2, 2],
       [2, 2]])

#matrix operation-addition

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[6,7]])
print(a+b)

[[ 4 10]
 [18 28]]


In [ ]:
#matrix multiplication
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[6,7]])
print(a@b)
print(a.dot(b))
print(a/b)

[[16 19]
 [36 43]]
[[16 19]
 [36 43]]
[[0.25       0.4       ]
 [0.5        0.57142857]]


In [ ]:
#matrix sub
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[6,7]])
print(a-b)

[[-3 -3]
 [-3 -3]]


In [ ]:
a=np.full([3,3,3],4,dtype=int)
a

array([[[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]]])

In [ ]:
a=np.full([3,3,3],4,dtype=float)
a

array([[[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]]])

In [ ]:
np.full([3,4],9,dtype=complex)

array([[9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j]])

In [ ]:
#3x4 matrix with value 9 using complex
a=np.full([3,4],9,dtype=complex)
a

array([[9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j]])

#identity matrix

In [ ]:
a=np.identity(3,dtype=int)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.identity(3,dtype=float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#create 4x4 matrix
y=np.array([[1,2,3,4],[2,3,4,5],[5,6,7,8],[2,7,6,5]])
print(y)
print(y.ndim)#row & column
print(y.size)
print(y.shape)
a=y.reshape(8,2)#we cant take 3,4 because array shape is 16 if we take 3,4 it will be only execute 12 elements
a

[[1 2 3 4]
 [2 3 4 5]
 [5 6 7 8]
 [2 7 6 5]]
2
16
(4, 4)


array([[1, 2],
       [3, 4],
       [2, 3],
       [4, 5],
       [5, 6],
       [7, 8],
       [2, 7],
       [6, 5]])

In [ ]:
a=np.array([[3,4,5],[5,7,8],[1,2,3],[6,7,5]])
a.reshape(6,2)

array([[3, 4],
       [5, 5],
       [7, 8],
       [1, 2],
       [3, 6],
       [7, 5]])

In [ ]:
#arange
a=np.arange(1,11,)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a=np.arange(1,11)
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
a=np.arange(1,11,1)
y=a.reshape(5,2)
y

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
a=np.array([[2.3,3.2,4.1],[2.1,4.5,6.1],[1.2,3.4,4.5]])
z=np.floor(a)
y=np.ceil(a)
print(z)
print(y)

[[2. 3. 4.]
 [2. 4. 6.]
 [1. 3. 4.]]
[[3. 4. 5.]
 [3. 5. 7.]
 [2. 4. 5.]]


In [ ]:
np.round(z) #towards even number

array([[2., 3., 4.],
       [2., 4., 6.],
       [1., 3., 4.]])

In [ ]:
a=np.arange(1,10).reshape(3,3)
print(a)
print("max of rows",a.max(axis=1))
print("max of column",a.max(axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
max of rows [3 6 9]
max of column [7 8 9]


In [10]:
#s
import numpy as np
a=np.array([[3,4,1],[5,3,1],[6,9,8]])
print(a)
b=np.sort(a,axis=0)
print(b)
c=np.sort(a,axis=1)
print(c)
d=np.argsort(a,axis=1)#index of sorted array,axis=1 for example the index of array [a] taken to the sorted array
print(d)

[[3 4 1]
 [5 3 1]
 [6 9 8]]
[[3 3 1]
 [5 4 1]
 [6 9 8]]
[[1 3 4]
 [1 3 5]
 [6 8 9]]
[[2 0 1]
 [2 1 0]
 [0 2 1]]
